
// FAVORITES

export const START_FAVORITES_REQUEST = 'START_FAVORITES_REQUEST'
export const END_RETRIEVE_FAVORITES_REQUEST = 'END_RETRIEVE_FAVORITES_REQUEST'
export const END_SAVE_FAVORITES_REQUEST = 'END_SAVE_FAVORITES_REQUEST'
export const ADD_FAVORITE = 'ADD_FAVORITE'
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE'


// WORD

export const START_WORD_REQUEST = 'START_WORD_REQUEST'
export const END_WORD_REQUEST = 'END_WORD_REQUEST'


// WORD OF THE DAY

export const START_WORD_OF_THE_DAY_REQUEST = 'START_WORD_OF_THE_DAY_REQUEST'
export const END_WORD_OF_THE_DAY_REQUEST = 'END_WORD_OF_THE_DAY_REQUEST'